### PR TITLE
Fixes dependencies order

### PR DESCRIPTION
**Pull request by DiogoNeves**
Updated the requirements' versions in `requirements.txt` to fix the build (in Python 3.10).  

I tested running a query with a target and download set and it worked.

### CODE REVIEW

**Comment by cchyung** [comment]
Thanks for contributing to this! It's been a while since I've maintained so appreciate it :)

**Review by cchyung — APPROVED** [review]

**Comment by cchyung** [comment]
Ff to merge!  Also yes, I think that would make sense as well.  

To be honest - this is not a library I've used in a long while so don't have too many opinions on direction or feature set

**Comment by DiogoNeves** [comment]
I completely forgot I don't have permissions to merge 😅 
I did not finish the changes to number of tags in a way that I am confident fully works (I have a hack I used) so I may skip that change after all

**Comment by DiogoNeves** [comment]
@cchyung just a friendly ping 😀

**Comment by cchyung** [comment]
just went ahead and merged!

**Pull request merged**
